
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "6051071067@st.utc2.edu.vn"
}

###
GET http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ



###
POST http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Square Neck Back",
    "description": "Quan dep hai",
    "url": "https://preview.colorlib.com/theme/cozastore/images/xproduct-16.jpg.pagespeed.ic.AbLwZITYaU.webp",
    "price": 29.64,
    "type": "Women"
}

###
PUT http://localhost:5000/product_action/60f79afcd100ad430030cff1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Quan Ao Update",
    "description": "Quan dep Update",
    "url": "img.freepik.com/free-photo/three-young-beautiful-smiling-girls-trendy-summer-casual-jeans-clothes-sexy-carefree-women-posing-positive-models-sunglasses_158538-4730.jpg?size=626&ext=jpg",
    "price": 100000
}

###

DELETE http://localhost:5000/product_action/60f79afcd100ad430030cff1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


###
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


{
    "cart": [
        {
            "title": "Quan Ao 4",
            "price": 200000,
            "quantity": 2
        },
        {
            "title": "Quan Ao 4",
            "price": 500000,
            "quantity": 1
        }
    ]
}

###
PUT http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQyYzE3ZjFkZWJmMDNhOTg5NTUxNjYiLCJpYXQiOjE2MzE3NjUxMTF9.6W7_-cYJdUAEoJjJV9BM0cBUVsKSU_3XwGsp9unbdeo

{
    "_id": "6142c17f1debf03a98955166",
    "couponCode": 
            {
                "name": "LOVEYOUHATEYOU",
                "discount": 20
            }
}

###
POST http://localhost:5000/favorites/6107590bf24d640adc8160ef
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y

###
GET http://localhost:5000/favorites/find_favorite/61075887f24d640adc8160e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y


###
GET http://localhost:5000/favorites
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y



###
PUT http://localhost:5000/comment/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzIzNzAwMDB9._RmUA8RpsKBvlR32nknCR8QK543LQuD1XYS1aHecUd0

{
    "_id": "614bfa8186fcdd2364562d9c",
   
    "feedback": {
        
        "content": "form long 12a7"
    }
}

###
GET http://localhost:5000/comment/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MmVmZTQ2NDg2MjFiMzgwYThkMjkiLCJpYXQiOjE2MzIzNjQ1Mjh9.AkJbRMLgAiG640aoDnO5jA2L1G0Tme5iUQYJ_mPrt6c


###
DELETE  http://localhost:5000/comment/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzIzNzA0NTJ9.ENqx3SZln2VYjiUBTj-K5V6Kxe9uxNiKos1O3brfjts

{
    "_id": "614bfa8186fcdd2364562d9c",
    "_idFeedback": "614bfebeafb46d15109689ee"
}

###
POST  http://localhost:5000/comment/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MmVmZTQ2NDg2MjFiMzgwYThkMjkiLCJpYXQiOjE2MzIzNjQ1Mjh9.AkJbRMLgAiG640aoDnO5jA2L1G0Tme5iUQYJ_mPrt6c

{
    "content": "Haha from Long 12a09"
}


###
GET  http://localhost:5000/rating/all_rating/61075969f24d640adc8160f5
Content-Type: application/json
