
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "vodoanhoanglong10a9@gmail.com"
}

###
GET http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ



###
POST http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Square Neck Back",
    "description": "Quan dep hai",
    "url": "https://preview.colorlib.com/theme/cozastore/images/xproduct-16.jpg.pagespeed.ic.AbLwZITYaU.webp",
    "price": 29.64,
    "type": "Women"
}

###
PUT http://localhost:5000/product_action/60f79afcd100ad430030cff1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Quan Ao Update",
    "description": "Quan dep Update",
    "url": "img.freepik.com/free-photo/three-young-beautiful-smiling-girls-trendy-summer-casual-jeans-clothes-sexy-carefree-women-posing-positive-models-sunglasses_158538-4730.jpg?size=626&ext=jpg",
    "price": 100000
}

###

DELETE http://localhost:5000/product_action/60f79afcd100ad430030cff1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


###
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


{
    "cart": [
        {
            "title": "Quan Ao 4",
            "price": 200000,
            "quantity": 2
        },
        {
            "title": "Quan Ao 4",
            "price": 500000,
            "quantity": 1
        }
    ]
}

###
PUT http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQyYzE3ZjFkZWJmMDNhOTg5NTUxNjYiLCJpYXQiOjE2MzE3NjUxMTF9.6W7_-cYJdUAEoJjJV9BM0cBUVsKSU_3XwGsp9unbdeo

{
    "_id": "6142c17f1debf03a98955166",
    "couponCode": 
            {
                "name": "LOVEYOUHATEYOU",
                "discount": 20
            }
}

###
POST http://localhost:5000/favorites/6107590bf24d640adc8160ef
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y

###
GET http://localhost:5000/favorites/find_favorite/61075887f24d640adc8160e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y


###
GET http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y




###
GET  http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MmVmZTQ2NDg2MjFiMzgwYThkMjkiLCJpYXQiOjE2MzI4Mzg5MjF9.V__Wry8uTildQZlQc5kEdjEljGxMDieIL2iRPT1O41I




###
POST http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzI2Njk0Nzh9.tm5IfHzKIZqBgRtHuxDpV0vtARix-blJYBPlHqoDi1A

{
    "rating": 4,
    "content": "san pham dep qua",
    "createAt": "22:46:15, 28/9/2021"
}

###
PUT http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzI2Njk0Nzh9.tm5IfHzKIZqBgRtHuxDpV0vtARix-blJYBPlHqoDi1A

{
    "rating": 4,
    "content": "Dep qua",
    "createAt": "23:45:15, 27/9/2021"
}

###
GET http://localhost:5000/cart
Content-Type: application/json

###
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


{
    "createAt": "17:39:12, 4/10/2021",
    "totalPrice": 650
}

###
POST  http://localhost:5000/contact
Content-Type: application/json

{
    "fullName": "Test",
    "email": "test@example.com",
    "phone": "0909230102",
    "message": "Nothing"
}

###
GET http://localhost:5000/product_action/most_favorites
Content-Type: application/json


###
GET http://localhost:5000/product_action/discount_products
Content-Type: application/json

###
DELETE  http://localhost:5000/product_action/616128416ad60e3c2c24be9d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


###
POST http://localhost:5000/product_action/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "CHRONO CERAMIC",
    "description": "The clock stands out in the dark",
    "type": "Watches",
    "size": ["30mm", "31mm","32mm"],
    "price": 328.33,
    "url": [
        {
            "color": "#e7e6eb",
            "img": [
                "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dwd169d09c/images/products/28000122_fr.jpg?sw=600&sh=600",
                "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw553d5776/images/products/28000122_s.jpg?sw=600&sh=600",
                "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw12f2d804/images/products/28000122_b.jpg?sw=600&sh=600",
                "https://www.mvmt.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dweb694286/images/products/28000122_l.jpg?sw=600&sh=600"
            ]
        }
        # {
        #     "color": "#717171",
        #     "img": [
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bdd506db-45c1-4600-95b9-8f6e59abb8be/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/1bc082b5-3be0-445c-9dc9-49dec6e7c7ca/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/62257571-64c2-436f-8ede-f5dcfd886370/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/2d9b1ce9-6002-4806-8302-55d4cf57d59e/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/611e90fb-1a27-4ef0-9c3f-9f6a8344e6f4/air-zoom-infinity-tour-golf-shoe-xbMdtR.png"
        #     ]
        # },
        # {
        #     "color": "#4ED0D2",
        #     "img": [
        #         "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5/40e3f1ee-a43c-4472-82d4-b65af9146104/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5,q_80/2d06cf6d-8f65-49a0-bb18-c264a14f425d/air-zoom-infinity-tour-golf-shoe-xbMdtR.png",
        #         "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,b_rgb:f5f5f5,q_80/c2c66419-017f-471b-809b-83501464b49a/air-zoom-infinity-tour-golf-shoe-xbMdtR.png"
        #     ]
        # }
        # {
        #     "color": "#A30327",
        #     "img": [
        #         "https://img.ltwebstatic.com/images3_pi/2021/09/17/1631856194d770d7a827de5c9622ace2a61ab5f6c3_thumbnail_600x.webp",
        #         "https://img.ltwebstatic.com/images3_pi/2021/09/17/16318561950ba198ed39f1d479bb3f8c561c86a2fc_thumbnail_600x.webp",
        #         "https://img.ltwebstatic.com/images3_pi/2021/09/17/16318561977c83f8595f75d34ad41aeac5431c19ec_thumbnail_600x.webp",
        #         "https://img.ltwebstatic.com/images3_pi/2021/09/17/16318561995fe4578cd8b55886d252c235138073cb_thumbnail_600x.webp",
        #         "https://img.ltwebstatic.com/images3_pi/2021/09/17/1631856201c34319d52690fbf5db3cf7ffe74ec46e_thumbnail_600x.webp"
        #     ]
        # }
        # {
        #     "color": "#C1C5C2",
        #     "img": [
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/00908861-8d1a-48e2-aa63-9f70c0d93298/zion-1-pf-basketball-shoe-bHGvxg.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/9e356619-099c-44b7-9537-00f0a14d191f/zion-1-pf-basketball-shoe-bHGvxg.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/65ca5b67-9986-4020-84c4-b08c959c2de9/zion-1-pf-basketball-shoe-bHGvxg.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/50a91473-d5bd-4b15-87b9-e0886670c22b/zion-1-pf-basketball-shoe-bHGvxg.png",
        #         "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/cc153d4f-ca8f-451f-9be3-adfbd3b88c54/zion-1-pf-basketball-shoe-bHGvxg.png"
        #     ]
        # }
    ]
}