
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "vodoanhoanglong10a9@gmail.com"
}

###
GET http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ



###
POST http://localhost:5000/product_action
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Square Neck Back",
    "description": "Quan dep hai",
    "url": "https://preview.colorlib.com/theme/cozastore/images/xproduct-16.jpg.pagespeed.ic.AbLwZITYaU.webp",
    "price": 29.64,
    "type": "Women"
}

###
PUT http://localhost:5000/product_action/60f79afcd100ad430030cff1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ

{
    "title": "Quan Ao Update",
    "description": "Quan dep Update",
    "url": "img.freepik.com/free-photo/three-young-beautiful-smiling-girls-trendy-summer-casual-jeans-clothes-sexy-carefree-women-posing-positive-models-sunglasses_158538-4730.jpg?size=626&ext=jpg",
    "price": 100000
}

###

DELETE http://localhost:5000/product_action/60f79afcd100ad430030cff1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


###
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


{
    "cart": [
        {
            "title": "Quan Ao 4",
            "price": 200000,
            "quantity": 2
        },
        {
            "title": "Quan Ao 4",
            "price": 500000,
            "quantity": 1
        }
    ]
}

###
PUT http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQyYzE3ZjFkZWJmMDNhOTg5NTUxNjYiLCJpYXQiOjE2MzE3NjUxMTF9.6W7_-cYJdUAEoJjJV9BM0cBUVsKSU_3XwGsp9unbdeo

{
    "_id": "6142c17f1debf03a98955166",
    "couponCode": 
            {
                "name": "LOVEYOUHATEYOU",
                "discount": 20
            }
}

###
POST http://localhost:5000/favorites/6107590bf24d640adc8160ef
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y

###
GET http://localhost:5000/favorites/find_favorite/61075887f24d640adc8160e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y


###
GET http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzE4OTE0MDV9.jCdcLvSz23SYubCcprRRwp5xUFswHEoGDv-4tfRQ_-Y




###
GET  http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MmVmZTQ2NDg2MjFiMzgwYThkMjkiLCJpYXQiOjE2MzI4Mzg5MjF9.V__Wry8uTildQZlQc5kEdjEljGxMDieIL2iRPT1O41I




###
POST http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzI2Njk0Nzh9.tm5IfHzKIZqBgRtHuxDpV0vtARix-blJYBPlHqoDi1A

{
    "rating": 4,
    "content": "san pham dep qua",
    "createAt": "22:46:15, 28/9/2021"
}

###
PUT http://localhost:5000/rating/61075969f24d640adc8160f5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ0MzIzZDQ2NDg2MjFiMzgwYThkM2UiLCJpYXQiOjE2MzI2Njk0Nzh9.tm5IfHzKIZqBgRtHuxDpV0vtARix-blJYBPlHqoDi1A

{
    "rating": 4,
    "content": "Dep qua",
    "createAt": "23:45:15, 27/9/2021"
}

###
GET http://localhost:5000/cart
Content-Type: application/json

###
POST http://localhost:5000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGY2NGVjNTdmMjNiYzIzY2M1ZTkzMDEiLCJpYXQiOjE2MjY4MzU1MjR9.kfSPVHQQ8DiEuZe8I6vcjIGzrBLzoFZQl5NU0p8WicQ


{
    "createAt": "17:39:12, 4/10/2021",
    "totalPrice": 650
}

###
POST  http://localhost:5000/contact
Content-Type: application/json

{
    "fullName": "Test",
    "email": "test@example.com",
    "phone": "0909230102",
    "message": "Nothing"
}

###
GET http://localhost:5000/product_action/most_favorites
Content-Type: application/json